filter:
    excluded_paths:
        - "dist/*"
checks:
    javascript:
        no_param_assign: true
        no_loop_var_assign: true
        no_implicit_undefined_return: true
        no_else_return: true
        no_alert: true
        eqeqeq: true
        no_var: true
                    
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [js-scrutinizer-run]
