filter:
    paths: ["src/*"]
    excluded_paths:
        - "tests/"
                    
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [js-scrutinizer-run]
